services:
  app:
    container_name: cv-app
    restart: always
    image: build
    build:
      context: .
      dockerfile: Dockerfile
    user: appuser
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: cv-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=cv_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
    command: ["postgres", "-c", "listen_addresses=*", "-c", "max_connections=200"] # Adjust configuration if needed
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: